"""Update Photo model for upload support

Revision ID: 1cd1f8d41f5a
Revises: 7d82bd4ca2b5
Create Date: 2025-11-23 18:31:06.222682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cd1f8d41f5a'
down_revision: Union[str, None] = '7d82bd4ca2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('filename', sa.Text(), nullable=False))
    op.add_column('photos', sa.Column('blob_name', sa.Text(), nullable=False))
    op.add_column('photos', sa.Column('blob_url', sa.Text(), nullable=False))
    op.add_column('photos', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('photos', sa.Column('content_type', sa.Text(), nullable=False))
    op.add_column('photos', sa.Column('exif_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('photos', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('photos', 'album_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('photos', 'blob_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('photos', 'mime',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('photos', 'exif_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('exif_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('photos', 'mime',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('photos', 'blob_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('photos', 'album_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('photos', 'updated_at')
    op.drop_column('photos', 'exif_data')
    op.drop_column('photos', 'content_type')
    op.drop_column('photos', 'file_size')
    op.drop_column('photos', 'blob_url')
    op.drop_column('photos', 'blob_name')
    op.drop_column('photos', 'filename')
    # ### end Alembic commands ###
