"""Add thumbnail_url to Photo

Revision ID: d083aaba43e8
Revises: 1cd1f8d41f5a
Create Date: 2025-11-23 18:37:14.096607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd083aaba43e8'
down_revision: Union[str, None] = '1cd1f8d41f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'thumbnail_url')
    # ### end Alembic commands ###
